# Generated by Django 5.2.1 on 2026-06-14 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0001_initial'),
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('pickup', '取件开箱'), ('manual', '人工开箱')], max_length=20)),
                ('operator', models.CharField(blank=True, max_length=100)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('locker_cell', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='open_audit_logs', to='lockers.lockercell')),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_audit_logs', to='parcels.parcel')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
    ]
